

FROM node:8.16.2-jessie-slim

RUN apt-get update  && apt-get install -y nginx

# RUN npm install puppeteer --unsafe-perm=true --allow-root

RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN cnpm i puppeteer

RUN apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

WORKDIR /app
COPY . /app/
EXPOSE 80
RUN  npm install  
RUN npm run build:test
RUN  cp -r dist/* /usr/share/nginx/html
RUN rm /etc/nginx/sites-enabled/default && cp default.conf /etc/nginx/sites-enabled/ && rm -rf /app
CMD ["nginx","-g","daemon off;"]